import { version } from '../src/index.js'

import * as test from '../src/svelte.js'

const spec = {
  // @magic/test svelte exports
  compileSvelte: 'fn',
  // isInitialized: 'fn',
  mount: 'fn',
  createSnippet: 'fn',
  tick: 'fn',
  html: 'fn',
  text: 'fn',
  component: 'fn',
  props: 'fn',
  fireEvent: 'fn',
  click: 'fn',
  dblClick: 'fn',
  contextMenu: 'fn',
  mouseDown: 'fn',
  mouseUp: 'fn',
  mouseMove: 'fn',
  mouseEnter: 'fn',
  mouseLeave: 'fn',
  mouseOver: 'fn',
  mouseOut: 'fn',
  keyDown: 'fn',
  keyPress: 'fn',
  keyUp: 'fn',
  type: 'fn',
  input: 'fn',
  change: 'fn',
  blur: 'fn',
  focus: 'fn',
  focusIn: 'fn',
  focusOut: 'fn',
  submit: 'fn',
  pointerDown: 'fn',
  pointerUp: 'fn',
  pointerMove: 'fn',
  pointerOver: 'fn',
  pointerOut: 'fn',
  touchStart: 'fn',
  touchEnd: 'fn',
  touchMove: 'fn',
  copy: 'fn',
  cut: 'fn',
  paste: 'fn',
  dragStart: 'fn',
  drag: 'fn',
  dragEnd: 'fn',
  dragOver: 'fn',
  dragEnter: 'fn',
  dragLeave: 'fn',
  drop: 'fn',
  resize: 'fn',
  scroll: 'fn',
  animationStart: 'fn',
  animationEnd: 'fn',
  animationIteration: 'fn',
  transitionEnd: 'fn',
  play: 'fn',
  pause: 'fn',
  ended: 'fn',
  volumeChange: 'fn',
  checked: 'fn',
  trigger: 'fn',
  testExportsPreprocessor: 'fn',
  // sveltekitMocksPreprocessor: 'fn',
  browser: 'bool',
  dev: 'bool',
  prod: 'bool',
  createStaticPage: 'fn',
  ensureSvelte: 'fn',
}

export default version({ ...test }, spec)
