language: cpp

os:
  - linux
  # not yet, test on mac os x directly.
  # - osx

env:
  matrix:
    - NODE_VERSION="8"
    - NODE_VERSION="9"
    - NODE_VERSION="10"

matrix:
  fast_finish: true

install:
  - npm install
  - npm link

script:
  - npm test

after_success:
  - npm run calls
