language: node_js

node_js:
  - "12.2"

os:
  - linux
  - osx

env:
  matrix:
    - NODE_VERSION="12.2"

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls
