export { default as is } from '@magic/types'
export { default as deep } from '@magic/deep'
export { default as fs } from '@magic/fs'
export { default as error } from '@magic/error'
export { run } from './run.js'
export const log: import('@magic/log').Log
export const isProd: boolean
export const isTest: boolean
export const isDev: boolean
export { curry, env, http, mock, promise, Store, vals, version, tryCatch } from './lib/index.js'
export { initDOM, getDocument, getWindow, isInitialized } from './lib/dom/index.js'
export {
  compileSvelte,
  mount,
  createSnippet,
  tick,
  html,
  text,
  component,
  props,
  fireEvent,
  click,
  dblClick,
  contextMenu,
  mouseDown,
  mouseUp,
  mouseMove,
  mouseEnter,
  mouseLeave,
  mouseOver,
  mouseOut,
  keyDown,
  keyPress,
  keyUp,
  type,
  input,
  change,
  blur,
  focus,
  focusIn,
  focusOut,
  submit,
  pointerDown,
  pointerUp,
  pointerMove,
  pointerOver,
  pointerOut,
  touchStart,
  touchEnd,
  touchMove,
  copy,
  cut,
  paste,
  dragStart,
  drag,
  dragEnd,
  dragOver,
  dragEnter,
  dragLeave,
  drop,
  resize,
  scroll,
  animationStart,
  animationEnd,
  animationIteration,
  transitionEnd,
  play,
  pause,
  ended,
  volumeChange,
  checked,
  trigger,
  testExportsPreprocessor,
  sveltekitMocksPreprocessor,
  browser,
  dev,
  prod,
  createStaticPage,
} from './lib/svelte/index.js'
//# sourceMappingURL=index.d.ts.map
